### ISSUE TITLE
keyboard light turns off after some time.

### ISSUE THREAD

**Issue by felipetrentin** [pobrn/ite8291r3-ctl#21] opened 2024-09-14 18:10 UTC
First of all, this driver has been a lifesaver, a huge thank you to all developers.

the driver works fine, even turning of the keyboard when the lid is closed and the ability to be controlled with function keys. however, after some minutes of inactivity on the keyboard, the brightness is set to zero, and after pressing any key, the brightness goes to the max value.

Is there any way to make this an option? so i can disable this behavior.

**Comment by pobrn** [comment] 2024-09-15 12:54
Duplicate of #4.

**Closed as not planned by pobrn** 2024-09-15 12:54 UTC
